* tf.keras.preprocessing.text.text_to_word_sequence(
    input_text,
    filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n',
    lower=True,
    split=' '
)

In [1]:
import numpy
import tensorflow as tf
from numpy import array
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Flatten,Embedding

# 주어진 문장을 '단어'로 토큰화하기
# 케라스의 텍스트 전처리와 관련한 함수중 text_to_word_sequence 함수를 불러옴
from tensorflow.keras.preprocessing.text import text_to_word_sequence

# 전처리할 텍스트를 정합니다.
text = '해보지 않으면 해낼 수 없다'

# 해당 텍스트를 토큰화 합니다. 
result = text_to_word_sequence(text)
print ('\n 원문 : \n', text)
print ('\n 토큰화 : \n', result)

2023-10-19 09:33:35.579257: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.



 원문 : 
 해보지 않으면 해낼 수 없다

 토큰화 : 
 ['해보지', '않으면', '해낼', '수', '없다']


In [2]:
# 단어 빈도수 세기
# 전처리 하려는 세개의 문장을 정합니다. 
docs = ['먼저 텍스트의 각 단어를 나누어 텍스트의 단위를 토큰화 합니다.',
        '텍스트의 단어로 토큰화 해야 딥러닝에서 인식됩니다.',
        '토큰화 한 결과는 딥러닝에서 사용할 수 있습니다.']

In [3]:
# 토큰화 함수를 이용해 전처리 하는 과정입니다.
token = Tokenizer() # 토큰화 함수 지정
token.fit_on_texts(docs) # 토큰화 함수에 문장 적용

# 단어의 빈도수를 계산한 결과를 각 옵션에 맞추어 출력합니다. 
print("\n단어 카운트:\n", token.word_counts)
# Tokenizer()의 word_counts 함수는 순서를 기억하는 OrderedDict클래스를 사용합니다.

# 출력되는 순서는 랜덤입니다.
print("\n문장 카운트 :", token.document_count)
print("\n각 단어가 몇 개의 문장에 포함되어 있는가:\n", token.word_docs)
print("\n각 단어에 매겨진 인덱스 값: \n", token.word_index)


단어 카운트:
 OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화', 3), ('합니다', 1), ('단어로', 1), ('해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])

문장 카운트 : 3

각 단어가 몇 개의 문장에 포함되어 있는가:
 defaultdict(<class 'int'>, {'단어를': 1, '나누어': 1, '토큰화': 3, '각': 1, '합니다': 1, '먼저': 1, '텍스트의': 2, '인식됩니다': 1, '단어로': 1, '딥러닝에서': 2, '해야': 1, '수': 1, '사용할': 1, '결과는': 1, '있습니다': 1, '한': 1})

각 단어에 매겨진 인덱스 값: 
 {'토큰화': 1, '텍스트의': 2, '딥러닝에서': 3, '먼저': 4, '각': 5, '단어를': 6, '나누어': 7, '합니다': 8, '단어로': 9, '해야': 10, '인식됩니다': 11, '한': 12, '결과는': 13, '사용할': 14, '수': 15, '있습니다': 16}


* tf.keras.preprocessing.text.Tokenizer(
    num_words=None,
    filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n',
    lower=True,
    split=' ',
    char_level=False,
    oov_token=None,
    analyzer=None,
    **kwargs
)

* num_words : 한계를 줌 -> 단어의 빈도수에 따라 제거. 즉, 많이 사용하지 않은 단어는 삭제

In [6]:
# 문장의 원-핫 인코딩
from tensorflow.keras.preprocessing.text import Tokenizer

text = "오랫동안 꿈꾸는 저는 그 꿈을 닮아간다"

token = Tokenizer()
token.fit_on_texts([text])
print('문장의 토큰화 :', token.word_index)

# 각 단어를 숫자화 
x = token.texts_to_sequences([text])
print('문장의 숫자화:', x)

# 원-핫 인코딩 방식으로 표현하면
from tensorflow.keras.utils import to_categorical

word_size = len(token.word_index) + 1
x = to_categorical(x, num_classes = word_size)
print('문장의 원-핫 인코딩:\n', x)

문장의 토큰화 : {'오랫동안': 1, '꿈꾸는': 2, '저는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}
문장의 숫자화: [[1, 2, 3, 4, 5, 6]]
문장의 원-핫 인코딩:
 [[[0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 1.]]]
